### ISSUE TITLE
Check that I installed numpy correctly

### ISSUE THREAD

**Issue by kwoychesko** [bpmi/account-financial-tools#2]
I was getting an error when processing a Loan transaction--we use [Account Loan Management by OCA](https://hamiltonfilmstudios.com/web?debug#id=347&view_type=form&model=ir.module.module&menu_id=45&action=31) and there is a requirement to install numpy (pip install numpy). I executed the command on the new Odoo server on Digital Ocean, but now I'm not sure I should have--do all Odoo instances use the same python instance? Should I have done something different? Because I am currently still getting the following error when trying to generate a monthly entry for a loan: NameError: name 'numpy' is not defined

**Comment by rga-odoo** [comment]
@kwoychesko  I have installed NumPy properly

**Comment by kwoychesko** [comment]
@rga-odoo Excellent thank you! I was able to successfully create Loan JE’s now. Thanks!
